{% set name = "python-hostlist" %}
{% set version = "1.20" %}
{% set sha256 = "5653db78e44cf16e3196d2e851aad3b5e38691f9e47b94cf952bf0d461562b52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed  .

requirements:
  host:
    - python
    - pip
  run:
    - python
    
test:
  commands:
    - python run_test.py
  
about:
  home: https://www.nsc.liu.se/~kent/python-hostlist/
  license: GPL2+
  license_family: GPL
  license_file: LICENSE.md
  summary: The Python module hostlist.py knows how to expand and collect LLNL hostlists, as used by SLURM, pdsh, powerman, and genders, among other projects

extra:
  recipe-maintainers:
    - iparask
