{% set name = "python-hostlist" %}
{% set version = "2.2.1" %}
{% set sha256 = "bbf7ca58835f84c6991084a661b409bc9cb3359c9f71be9b752442ba9225a0a5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed  .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - python run_test.py

about:
  home: https://www.nsc.liu.se/~kent/python-hostlist/
  license: GPL2+
  license_family: GPL
  license_file: LICENSE.md
  summary: The Python module hostlist.py knows how to expand and collect LLNL hostlists, as used by SLURM, pdsh, powerman, and genders, among other projects

extra:
  recipe-maintainers:
    - iparask
